#Import everything
from UrsinaNetworking import UrsinaNetworkingServer
from UrsinaNetworking import UrsinaNetworkingClient

from UrsinaNetworking import EasyUrsinaNetworkingClient
from UrsinaNetworking import EasyUrsinaNetworkingServer
